ecodor:
  openapi:
    dev-url: http://localhost:8080

spring:
  application:
    name: main-service


#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/example
#    username: example
#    password: password
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    filter: true
    path: /swagger-ui.html
    tryItOutEnabled: true
